language: objective-c
osx_image: xcode7.1
env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - PROJECT=Fargo.xcodeproj
    - IOS_FRAMEWORK_SCHEME="Fargo-iOS"
    - OSX_FRAMEWORK_SCHEME="Fargo-OSX"
    - TVOS_FRAMEWORK_SCHEME="Fargo-tvOS"
    - WATCHOS_FRAMEWORK_SCHEME="Fargo-watchOS"
    - IOS_SDK=iphonesimulator9.1
    - OSX_SDK=macosx10.11
    - TVOS_SDK=appletvsimulator9.0
    - WATCHOS_SDK=watchsimulator2.0
  matrix:
    - DESTINATION="OS=8.1,name=iPhone 4S"       	SCHEME="$IOS_FRAMEWORK_SCHEME" 	SDK="$IOS_SDK"	ACTION="test"
    - DESTINATION="OS=8.2,name=iPhone 5"        	SCHEME="$IOS_FRAMEWORK_SCHEME" 	SDK="$IOS_SDK"	ACTION="test"
    - DESTINATION="OS=8.3,name=iPhone 5S"       	SCHEME="$IOS_FRAMEWORK_SCHEME" 	SDK="$IOS_SDK"	ACTION="test"
    - DESTINATION="OS=8.4,name=iPhone 6"        	SCHEME="$IOS_FRAMEWORK_SCHEME" 	SDK="$IOS_SDK"	ACTION="test"
    - DESTINATION="OS=9.0,name=iPhone 6 Plus"   	SCHEME="$IOS_FRAMEWORK_SCHEME" 	SDK="$IOS_SDK"	ACTION="test"
    - DESTINATION="OS=9.1,name=iPhone 6S"       	SCHEME="$IOS_FRAMEWORK_SCHEME" 	SDK="$IOS_SDK"	ACTION="test"
    - DESTINATION="arch=x86_64"                 	SCHEME="$OSX_FRAMEWORK_SCHEME" 	SDK="$OSX_SDK"	ACTION="test"
    - DESTINATION="OS=9.0,name=Apple TV 1080p"		SCHEME="$TVOS_FRAMEWORK_SCHEME" SDK="$OSX_SDK"	ACTION="test"
    - DESTINATION="OS=2.0,name=Apple Watch - 38mm"	SCHEME="$WATCHOS_FRAMEWORK_SCHEME" SDK="$WATCHOS_SDK" ACTION="build"
before_install:
    - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
    - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
    - set -o pipefail
    - xcodebuild -version
    - xcodebuild -showsdks

    # Build & Test
    - xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO $ACTION | xcpretty -c;

    # Pod lint
    - pod lib lint;